### ISSUE TITLE
enum positions for people

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#117]
This way we can have one source of truth.

**Comment by CJ-Wright** [comment]
It turns out that we have this here: https://github.com/regro/regolith/blob/master/regolith/sorters.py#L29
However this should be enumerated in the schema so that it gets documented properly. Please feel free to put in a PR is there are any entries missing in the positions. I will try to put this so that the dict is used to build the enum in the schema (so there is one source of truth for all the positions).
