### ISSUE TITLE
Default name should be provided when name key is not found in people database.

### ISSUE THREAD

**Issue by sandraskj** [regro/regolith#629]
Currently it leads to an error message when using builder internalhtml. We need to set prsn["name"] to something when it is not found in the people database.

**Comment by connorjbracy** [comment]
Is this a thing we want to handle in regolith? It feels very similar to the case of an incorrect `doi` entry which I think you said you want `build internalhtml`  to fail when it comes across a bad `doi`  rather than handling it and moving on. In exploring the way that the linked issue manifests, it seems like it breaks when there is an incorrect group member id specified in, say, the `lead` field so it would make sense to me that the build should fail in this case rather than "providing a default name" and moving on as the issue description seems to suggest

**Comment by sbillinge** [comment]
I will check this and get back to you.  Probs we want it to blow up

**Comment by sbillinge** [comment]
Closing.  This is correct behavior.  If prsn["name"] is missing the db needs to be updated!
