### ISSUE TITLE
`NotADirectory` errors poduced by tests/test_commands.py

### ISSUE THREAD

**Issue by N-G-Asker** [regro/regolith#937]
Running `python run_tests.py` from a synchronized clone results in failed tests due to `NotADirectoryError`s.
```
====================================================================== short test summary info =======================================================================
FAILED tests/test_commands.py::test_fs_to_mongo_python - NotADirectoryError: [Errno 20] Not a directory: False
FAILED tests/test_commands.py::test_mongo_to_fs_python - NotADirectoryError: [Errno 20] Not a directory: False
================================================= 2 failed, 462 passed, 33 skipped, 11 warnings in 104.23s (0:01:44) =================================================
```

**Comment by sbillinge** [comment]
I checked out upstream master and ran tests successfully without this error on windows (git bash).  It is also passing CI on Travis (see your own commit).   This may be a bug but is probably more likely to be some kind of local setup issue on your computer.  That is where I would look first to resolve it.

**Comment by sbillinge** [comment]
In the code we skip mongo imports when users don't have mongo.  This is a feature so that you only need that as a dependency if you are running a mongo backend.  

I am not sure I agree that it is a feature that we skip tests because our core developers don't have pymongo installed.  It is much better that code is tested than not tested.  It is a two minute job for a dev minded person  to install pymongo in their env.  

I agree consistency is good, so perhaps we shouldn't be skipping those other mongo tests.....

**Comment by N-G-Asker** [comment]
Okay, I'll grab pymongo for my environment and report back!

**Comment by sbillinge** [comment]
Are we ready to close this now?

**Comment by N-G-Asker** [comment]
For posterity, what I did to install the proper package was:
`conda install -c conda-forge mongodb`

Now I'm running into issue #944 -- but we've already been there and done that, so the good news is I have the solution and am working that now.

I do not want to close this issue until I am successfully running all tests.

**Comment by sbillinge** [comment]
please paste the stack dump here so we can make sure that it is the same error we had before.

**Comment by N-G-Asker** [comment]
For further troubleshooting and resolution, see issue #944
